# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_brands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Brands',
            new_name='Certificate',
        ),
    ]
