# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0012_auto_20160127_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
