# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0013_auto_20160127_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
