# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0015_auto_20160127_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='path',
        ),
        migrations.RemoveField(
            model_name='article',
            name='path',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='path',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='path',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='path',
        ),
        migrations.RemoveField(
            model_name='map',
            name='path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='path',
        ),
    ]
