# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0016_auto_20160127_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
