# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0017_auto_20160127_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
