# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0023_menu_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
