# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0026_auto_20160127_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='page',
            field=models.ManyToManyField(to='care.Pages'),
        ),
    ]
