# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0029_auto_20160128_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
