# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0030_remove_about_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
    ]
