# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0031_auto_20160128_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
