# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0032_auto_20160128_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.List'),
        ),
    ]
