# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0033_auto_20160128_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterField(
            model_name='about',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
