# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0035_about_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='created_by',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
        migrations.AddField(
            model_name='brand',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
        migrations.AddField(
            model_name='contact',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
        migrations.AddField(
            model_name='map',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
        migrations.AlterField(
            model_name='about',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
    ]
