# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0037_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='page',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ManyToManyField(blank=True, null=True, to='care.Pages'),
        ),
    ]
