# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0038_auto_20160128_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hello',
            field=models.ManyToManyField(blank=True, to='care.Banner'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='page',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care.Pages'),
        ),
    ]
